import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./../styles/globals.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <body className={``}>
        {/* <SessionProvider session={session}> */}
        {children}
        {/* </SessionProvider> */}
        <Toaster />
      </body>
    </html>
  );
}
