export const imageConfig = {
  notificationPng: "/img/notification.png",
  userPng: "/img/user.png",
  deleteGif: "/img/arfat-delete-gif.gif",
  mePNG: `/img/me.png`,
  resumePDF: "/img/resume.pdf",
  noImgaePNG: "/img/noimage.png",
  pythonSVG: "/img/python.svg",
  firebaseSVG: "/img/firebase.svg",
  mongoDbSVG: "/img/mongodb.svg",
  reduxSVG: "/img/redux.svg",
  reactSVG: "/img/react.svg",
  javascriptSVG: "/img/js.svg",
  whitePNG: "/img/white.png",
  logoPNG: "/img/logo.png",
  coderJPG: "/img/coder.jpg",
};
