import MainLayoutComponent from "@/components/mainLayoutComponent";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return <MainLayoutComponent>{children}</MainLayoutComponent>;
}
